name: Rust_Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "25 4 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cargo cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: update rust
      run: rustup update
      
    - name: install wasm-pack
      run: cargo install wasm-pack
      
    - name: build
      run: npm run build
